sudo: false
language: php
php:
    - 5.4

branches:
    only:
        - master

cache:
    directories:
        - vendor
        - bin

before_script:
    - composer install --prefer-source

script:
    - bin/phpspec run -fpretty --verbose
